version: "3"
services:
  app:
      image: node:alpine
      volumes:
        - ./:/app
      working_dir: /app
      depends_on:
        - mongo
      environment:
        NODE_ENV: development
      ports:
        - 3500:3500
      command: npm run dev
  mongo:
      image: mongo
      expose:
        - 27017
      volumes:
        - ./data/db:/data/db